name: Deploy site to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Assuming the site is already built
    #- name: Install dependencies
    #  run: npm install

    #- name: Build project
    #  run: npm run build

    - name: Deploy to Production via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.filiprosa.cz
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        # Nahráváme pouze obsah složky 'out', kterou vytvořil build
        local-dir: ./out/
        server-dir: /www/subdom/new/
        # Vyloučíme věci, které na serveru nechceme přepsat (např. configy)
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .htaccess
